/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    VitaButton: typeof import('./src/components/ui/VitaButton.vue')['default']
    VitaCard: typeof import('./src/components/VitaCard.vue')['default']
    VitaLogo: typeof import('./src/components/VitaLogo.vue')['default']
    VitaPrice: typeof import('./src/components/VitaPrice.vue')['default']
    VitaProductAdd: typeof import('./src/components/VitaProductAdd.vue')['default']
    VitaProductList: typeof import('./src/components/VitaProductList.vue')['default']
  }
}
